# Generated by Django 5.0.6 on 2025-09-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ADMINISTRATIVE', 'Administrative')], max_length=20)),
                ('professor_type', models.CharField(choices=[('NONE', 'None'), ('PERMANENT', 'Permanent'), ('CONTRACTOR', 'Contractor')], default='NONE', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.area')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.office')),
            ],
        ),
    ]
